### ISSUE TITLE
qBittorrent custom path missing forward slash

### ISSUE THREAD

**Issue by Oxyden4ik** [tympanix/Electorrent#183] opened 2020-05-24 08:04 UTC
**Client: Electorrent**
- [ ] µTorrent
- [x] qBittorrent
- [ ] Transmission
- [ ] rTorrent
- [ ] Deluge

**Client Version:** 2.7.1

**Operating System:** server OS Debian 9, client OS Win 10

**Application Version:** qbittorrent (3.3.7-3+deb9u1)

**Description:** It's not connecting to server, Connection problem. But all settings is correct, the same as in web gui. Look screenshot
https://sun1-94.userapi.com/P3MeC4-BgsQfN5eArBAn729B7w8nGBW9TqIIug/B5nzEYIvmoU.jpg

**Comment by tympanix** [comment] 2020-05-24 09:24
Your qBittorrent is a bit old. It might still work though. I see you have configured the path to `/home/DLNA/2Tb/`. That might not be correct. Maybe simply try `/`?

**Comment by Oxyden4ik** [comment] 2020-05-24 09:38
qBittorrent the latest stable version for Debian 9. 
The value of the path is not active in the screenshot, and I tried first without it, just  / . 
Well, apparently the thing is in the qbittorent version, need to assemble a new one for my OS.

**Comment by SSoft7** [comment] 2020-06-23 10:59
@tympanix I can confirm this as well. The issue is as following.

When using a custom path, electorrent sends the following request
`https://host.qbt.com/qbittorrent/custompathapi/v2/auth/login`
instead of the following
`https://host.qbt.com/qbittorrent/custompath/api/v2/auth/login`

So, all you need to do is add a slash '/' properly when using path.

**Comment by tympanix** [comment] 2020-06-23 14:59
@SSoft7 nicely spotted!

Although, in the screenshot provided in this issue, the path has bot a trailing and leading `/`. Nevertheless, this should be fixed in the qBittorrent implementation.

**Closed** 2020-12-12 21:18 UTC
Labels: bug, qbittorrent
