### ISSUE TITLE
"Certificate expired" error with valid certificate

### ISSUE THREAD

**Issue by sensibleish** [tympanix/Electorrent#230] opened 2021-10-04 20:13 UTC
**Client:**
- [X] rTorrent

**Client Version:**
Unknown

**Operating System:**
Unknown, looks like some Linux flavor

**Application Version:**
Electorrent 2.7.2 on Mac OS 11.6

**Description:**
Electorrent is throwing a "certificate expired" error even though the remote server has a valid certificate. I suspect this is related to the issue discussed in https://techcrunch.com/2021/09/21/lets-encrypt-root-expiry/

I'm using Electorrent with a hosted rTorrent server. I do not have interactive shell login so I have minimal information about the server side. However, it worked fine for months. This is the first time in October I have tried it (i.e. after the September 30 certificate expiration mentioned in the article). If I use my Mac's certificate assistant to retrieve and evaluate the certificates from the server, it shows them as valid with a Let's Encrypt (ISRG) root CA:

![Valid certificate](https://user-images.githubusercontent.com/1753270/135918155-72e903e3-4fd2-4464-af80-30dcb5c2ca40.png)

Further guessing: Electorrent bundles its own set of root CA certs, and needs to update?

**Comment by phuze** [comment] 2021-10-30 17:32
I have the same issue and I've tried a couple things on my end to work around this problem.

**Manually installed LetsEncrypt's new root certificate**.
Typically Windows updates will ensure you've got updated root certificates, but I did this anyways for the sake of it.
1. Delete all expired `DST Root CA X3` certificates from your local machine.
2. Download the new root cert [from here](https://letsencrypt.org/certificates/#root-certificates) -- you're looking for `isrgrootx1.der`
3. Double click to install on your machine (Or import to `Trusted Root Certification Authorities`)

**Manually defining the certificate.**
I attempted to define the certificate within my electorrent `config.js`, by following the [Certificate Object](https://www.electronjs.org/docs/latest/api/structures/certificate) reference Electron documentation. Note that your user config for the Electorrent app will be found here: `C:\Users\<user>\AppData\Roaming\Electorrent\config.js`

Neither option worked here.

@tympanix Are you able to offer any insights? How can we resolve this issue?

**Comment by phuze** [comment] 2021-11-06 17:50
I'm getting dead project vibes.

**Comment by tympanix** [comment] 2021-11-09 15:53
@phuze Thank you for you detailed debugging.

The problem here is that NodeJS stores TLS certificates in the runtime and does not use the certificates provided by your operating system.

To fix the issue we have to update the NodeJS runtime, meaning, updating the Electron framework, which bundles NodeJS. I've tried updating the Electron dependency to fix the issue but no successful attempt yes (app keeps breaking).

I suggest that we update Electron to the lowest version, which has the fix for the expired Let's Encrypt certificate (to fix as few things as possible). I'm still trying to figure out which version of NodeJS (and therefore Electron) that is exactly.

P.S. Not a dead project per se, but the time and effort I have to maintain this in my spare time is limited. I hope we can find a solution which is suited for this. Sorry for the late reply.

**Comment by phuze** [comment] 2021-11-09 17:03
@tympanix Appreciate the follow up mate.

It looks like someone from the Postman team [identified a fix](https://github.com/electron/electron/issues/31212). A [patch](https://github.com/electron/electron/pull/31213) has been merged into Electron and backported to previous versions, including 13.x which this project is currently using. I'm thinking this just requires a rebuild so that patch gets rolled into the Electorrent app.

**Comment by tympanix** [comment] 2021-11-20 22:33
Got v2.7.3 released which should fix the problem. Feedback appreciated if you can confirm.
https://github.com/tympanix/Electorrent/releases/tag/v2.7.3

**Closed by tympanix** 2021-11-20 22:33 UTC

**Comment by WladyX** [comment] 2021-11-21 06:32
I can confirm all good now. Thank you!
